source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'pg'
gem 'activerecord-postgis-adapter'
gem 'rgeo'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rest-client'
gem 'merc_convert'
gem 'geocoder'

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
end

